# Generated by Django 5.2.7 on 2025-11-04 23:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('estado_civil', models.CharField(blank=True, max_length=30)),
                ('alcaldia', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_sem_cursado', models.IntegerField(blank=True, null=True)),
                ('sem_posible_abandono', models.IntegerField(blank=True, null=True)),
                ('ocupacion_actual', models.CharField(blank=True, max_length=100)),
                ('trabajo_actual', models.CharField(blank=True, max_length=100)),
                ('apoyo_actual', models.CharField(blank=True, max_length=100)),
                ('expectativas_carrera', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_actual', to='dashboards.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='FactoresDesercion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendimiento', models.TextField(blank=True)),
                ('financieros', models.TextField(blank=True)),
                ('personales', models.TextField(blank=True)),
                ('costos', models.TextField(blank=True)),
                ('salud_mental', models.TextField(blank=True)),
                ('falta_apoyo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factores_desercion', to='dashboards.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasAbiertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continuar_estudios', models.TextField(blank=True)),
                ('mensaje_ayuda', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_abiertas', to='dashboards.datospersonales')),
            ],
        ),
    ]
