# Generated by Django 5.2.7 on 2025-11-05 19:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_cuenta_egreso_ingreso_resumenmensual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='resumenmensual',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='saldo_inicial',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='dashboards.cuenta')),
            ],
        ),
        migrations.DeleteModel(
            name='Egreso',
        ),
        migrations.DeleteModel(
            name='Ingreso',
        ),
        migrations.DeleteModel(
            name='ResumenMensual',
        ),
    ]
