# Generated by Django 5.2.5 on 2025-08-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
