# Generated by Django 5.2.5 on 2025-08-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_profile_image_forumpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='media/profiles/'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ForumPost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
