# Generated by Django 5.2.5 on 2025-08-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='media/profiles/'),
        ),
    ]
